_G.EUI_AtlasMap = {
    ["uitools-icon-close"] = "Interface\\Buttons\\UI-Panel-MinimizeButton-Up",
    ["Azerite-PointingArrow"] = "Interface\\Buttons\\UI-SpellbookIcon-NextPage-Up",
    ["shop-card-wide-frame-default"] = "Interface\\DialogFrame\\UI-DialogBox-Background",
    ["shop-card-wide-frame-hover"] = "Interface\\DialogFrame\\UI-DialogBox-Background",
    ["lootroll-animreveal-a"] = "Interface\\TargetingFrame\\UI-StatusBar",

    ["Ui-Dialog-New-Background"] = "Interface\\DialogFrame\\UI-DialogBox-Background",
    ["UI-QuestTrackerButton-Secondary-Collapse"] = "Interface\\Buttons\\UI-MinusButton-Up",
    ["UI-QuestTrackerButton-Secondary-Expand"] = "Interface\\Buttons\\UI-PlusButton-Up",
    ["QuestLog-main-background"] = "Interface\\QuestFrame\\UI-QuestLog-Background",
    ["UI-RefreshButton"] = "Interface\\Buttons\\UI-RotationLeft-Button-Up",
    ["characterupdate_background"] = "Interface\\DialogFrame\\UI-DialogBox-Background",
    ["VAS-icon-checkmark-glw"] = "Interface\\RAIDFRAME\\ReadyCheck-Ready",
    ["charactercreate-icon-dice"] = "Interface\\Buttons\\UI-GroupLoot-Dice-Up",
    ["bag-main"] = "Interface\\Buttons\\Button-Backpack-Up",
    ["Crosshair_Quest_64"] = "Interface\\Icons\\INV_Misc_QuestionMark",
    ["UI-HUD-RotationHelper-Inactive-2x"] = "Interface\\Buttons\\UI-Quickslot-Depress",
    ["UI-HUD-ActionBar-IconFrame-Slot"] = "Interface\\Buttons\\UI-EmptySlot",
    ["common-icon-sound"] = "Interface\\OptionsFrame\\VoiceChat-Play",
    ["common-icon-sound-pressed"] = "Interface\\OptionsFrame\\VoiceChat-Down",
    ["Interface\\AnimaChannelingDevice\\AnimaChannelingDeviceLineVerticalMask"] = "Interface\\AddOns\\EllesmereUI\\media\\textures\\soft-line",
}
